# kombo — single image, two commands (serve | sync). See entrypoint.sh.
#
# Portable by design: the image carries its own Python + locked deps, so it runs
# identically on xavi today and on any container host later. No GEOS/shapely —
# the proximity math is pure Python (see app.py), so there are no compiled
# extension surprises across hosts.
FROM python:3.13-slim AS base

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VERSION=2.3.3 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1 \
    DATA_DIR=/data \
    PORT=8090

WORKDIR /app

# Deps first (own layer → cached unless the lock changes). Installs from
# poetry.lock into the system environment, main group only.
RUN pip install "poetry==${POETRY_VERSION}"
COPY pyproject.toml poetry.lock ./
RUN poetry install --only main --no-root

# App + pipeline. index.html / geojson / caches are intentionally NOT baked in
# (see .dockerignore) — the dataset lives on the mounted DATA_DIR volume and is
# (re)generated by `sync`.
COPY app.py geocode.py fetch_xlsx.py source.env entrypoint.sh ./

# Tier 0+1 hardening: run as a non-root, image-internal user (no host identity
# needed — DATA_DIR is private app state, not shared/tank data → no Tier-2 UID).
# cap_drop + no-new-privileges are applied at the compose layer.
RUN chmod +x entrypoint.sh \
    && useradd --uid 10001 --create-home --home-dir /home/app app \
    && mkdir -p /data && chown app:app /data

USER 10001
EXPOSE 8090
ENTRYPOINT ["./entrypoint.sh"]
CMD ["serve"]
